# Generated by Django 4.2.7 on 2024-02-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категории')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='IconAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Тип животного')),
                ('icon', models.ImageField(upload_to='media/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Иконка животного',
                'verbose_name_plural': 'Иконки животного',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Подкатегории')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('short_description', models.CharField(max_length=95, verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('compound', models.TextField(verbose_name='Состав')),
                ('applying', models.TextField(verbose_name='Применение')),
                ('waiting_time', models.TextField(verbose_name='Период ожидания')),
                ('release_form', models.TextField(verbose_name='Форма выпуска')),
                ('storage_date', models.TextField(verbose_name='Состав')),
                ('storage_conditions', models.TextField(verbose_name='Срок хранения')),
                ('is_new_product', models.BooleanField(verbose_name='Является ли продукт новинкой')),
                ('icon_animal', models.ManyToManyField(related_name='products', to='products.iconanimal', verbose_name='Иконка животного')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='Какой подкатегории относится?')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
    ]
